#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4 
#SBATCH --time=10:0:00
#SBATCH --error=%J.err
#SBATCH --output=%J.out
#SBATCH --job-name=job-test

module purge

module load qe/7.2

export OMP_NUM_THREADS=1
mpirun  pw.x  < rel_opt.inp > rel_opt.out 
